apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gitlab-app
  template:
    metadata:
      labels:
        app: gitlab-app
    spec:
      containers:
        - image: gitlab/gitlab-ce:18.7.5-ce.0
          name: gitlab-app
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://localhost:8080/'
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
          ports:
            - containerPort: 80