apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42-playground
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
  - host: wil42-playground.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil42-playground
            port:
              number: 80